baseURL = "https://cd2022.freethoughtlebanon.net"
languageCode = "en-us"
title = "Celebrating Dissent 2022"
theme = "dissent"

[params]
    copyrightHtml = 'Copyright &#xA9; 2022 Freethought Lebanon. All Rights Reserved.'